### PR TITLE
kernel4.comp: remove unused command

### PR DESCRIPTION
**Pull request by eliasnaur**

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Isn't circle and line also unused?

**Comment by eliasnaur** [comment]
> Isn't circle and line also unused?

Removed circle command as well. What line are you referring to?

**Comment by ishitatsuyuki** [comment]
`CmdLine`, apparently it's only in `ptcl.rs`.

**Comment by eliasnaur** [comment]
Thanks, done.

**Comment by raphlinus** [comment]
I'll probably want to bring circle and line back later as optimizations of special shapes, but they're not a priority at all and it's worth measuring how much of a speedup they represent over the general path mechanism.

The one that I *do* expect will have a significant impact is rectangle and probably rounded rectangle. But those can be brought back later.

**Review by raphlinus — APPROVED** [review]

**Pull request merged**
