### PR TITLE
Clarify licensing for WGSL shaders

### PR DESCRIPTION
**Pull request by eliasnaur**
The SPDX headers are shorter and clearer, IMHO. Let me know if this PR isn't appropriate or you'd like it done in another way.

### CODE REVIEW

**Review by raphlinus — APPROVED** [review]
Thanks for doing this. I'd like @dfrg to also thumbs-up, as a lot of the newer work is his.

**Comment by dfrg** [comment]
Absolutely. Looks good to me. Thanks Elias!

**Comment by dfrg** [comment]
This should probably target the dev branch though so it doesn't get out of sync.

**Comment by eliasnaur** [comment]
> This should probably target the dev branch though so it doesn't get out of sync.

Done.

**Review by DJMcNab — APPROVED** [review]
I'm the only other one to have 'worked' on these shaders (my contribution is only minor).

**Review by dfrg — APPROVED** [review]
I’ll also add an official stamp. Feel free to merge.

**Pull request merged**
