### PR TITLE
close gaps left by non-deterministic elements.comp monoid

### PR DESCRIPTION
**Pull request by eliasnaur**
This change fixes the gaps described in #62 for Gio.

However, I haven't figured out how to squeeze the FLAG_END_PATH flag into the scene.rs tag encoding. There is already the is_fill flag, but it's encoded as separate Rust enums, and I don't want to add another variant dimension (not-end-of-path vs end-of-path).

Please advice?

### CODE REVIEW

**Review by raphlinus — COMMENTED** [review]
This can't be merged as-is because it breaks Rust rendering. It is possible to pack more flags into the tag word, but this would require nontrivial work. I had started work on it but ripped it out. Alternatively I could hack the code to set the bit. Perhaps as an intermediate stage we could have a separate flags word, then an issue to make the encoding more efficient.

One question I have that's unresolved is how an open stroke is to be encoded.

Longer term I'm considering alternate solutions. One idea is to have a separate pass to generate the transforms, so there is one resolved transform per "transform" element in the input. This may have the desirable side effect of reducing the cost of computing the transform "monoid", as this is likely a large part of the total cost of element transform. I considered fixed point math for the transforms, but this doesn't feel right, especially as I'd imagine fixed point math may be much slower than floating.

I'm still chewing on this, but wanted to get a snapshot of my thoughts across.

**Comment by raphlinus** [comment]
Ok, I've done #69 so I can encode bits into the tag word, something that I think will generally be useful. I also locally patched this to set the flag for the last element on `close_path`, and I get this result:

image

There are two issues here. One is stray segments from stroked paths that aren't closed. This is as expected from reading the patch. Also, there are *more* artifacts related to closed paths not being watertight. I haven't tracked these down either.

So I have questions about how carefully this patch was tested. Were you able to get the tiger to render artifact free?

**Comment by eliasnaur** [comment]
Ugh, that's bad. No, I didn't test the tiger because I didn't figure out a way to pass the end path flag in Rust. This change does work great for all of Gio's tests, even with non-trivial transformations and lots of text. I don't use strokes yet, though, which is why I didn't notice the open path flaw.

Now, I can dig into the tiger rendering glitches if you like, but it sounds to me you've found a better fix than this change. If so, let's just abandon this change and not waste more time on it.

**Comment by raphlinus** [comment]
I don't have a good solution complete, but understand the problem space well enough I think the next major iteration of work on path filling robustness can take on this issue as well as #68. I agree with closing this PR for now, with appreciation for having discovered the problem and explored one avenue to solving it.

**Pull request closed without merging**
